### ISSUE TITLE
Demo not working 

### ISSUE THREAD

**Issue by jt-helsinki** [bergben/ng2-img-tools#12]
Hi

I am using a mac with Chrome v60 and Firefox v54. Although I can select the image in the demo, nothing else happens. I'm pretty sure this is not right.

Cheers

JT

**Comment by bergben** [comment]
Hi @paistipoikka,

thank you very much for reporting this issue. I had introduced some breaking changes for [ng2-file-input](https://github.com/bergben/ng2-file-input) and had completely forgotten to update the demo accordingly. The fileChange event was therefore not triggered. Everything should work fine now again!
