### ISSUE TITLE
ng2-img-tools vs ng2-img-max

### ISSUE THREAD

**Issue by caglarturkurka** [bergben/ng2-img-tools#16]
Hi, I want to learn that what are the differences between img-tools and img-max.Because I think that each of them  use for same issue or different.Please tell me which one is the best for resizing image.Thank you

**Comment by bergben** [comment]
Hello @caglarturkurka. 
ng2-img-tools depends on ng2-img-max. ng2-img-max has the resizing to a maximal height / width and compressing down to a certain filesize functionality. ng2-img-tools adds cropping, resizing to an exact width / height by keeping the ratio width : height options, which can come in very handy for creating thumbnails. 
I hope this clarifies the differences :)
