### ISSUE TITLE
Please support SSR (Server Side Rendering)

### ISSUE THREAD

**Issue by AnthonyNahas** [bergben/ng2-img-tools#19]
i am using this module for an angular universal app. The app will be first rendered with nodeJS, then will be sent to the client. Since on the server side, the "window", "document" objects are not available, i am getting this error now after the last update...

`window.pica = exports;
        ^

ReferenceError: window is not defined
    at Object.__webpack_require__.1../lib/js/resize_array `

thank you

**Comment by bergben** [comment]
Hey @AnthonyNahas, please refer to https://github.com/bergben/ng2-img-max/issues/11#issuecomment-335492378 for now... Thanks :)

**Comment by bergben** [comment]
Hey @AnthonyNahas. This is fixed with version 1.1.0.

**Comment by AnthonyNahas** [comment]
@bergben i tested it one more time with version 1.1.0 and i am getting a new error now -->

`server.js:189586
module.exports = ng2-img-tools/node_modules/ng2-pica/dist/src/img-exif.service;
                 ^

ReferenceError: ng2 is not defined`

i suggest to reopen the issue...
