### ISSUE TITLE
compiler.js:466 Uncaught Error: Unexpected value 'Ng2ImgToolsModule' imported by the module 'AppModule'. Please add a @NgModule annotation.

### ISSUE THREAD

**Issue by kaxu** [bergben/ng2-img-tools#22]
when i used 

>   "dependencies": {
    "@ angular/animations": "^5.0.0",
    "@ angular/cdk": "^2.0.0-beta.8",
    "@ angular/cli": "^1.5.0",
    "@ angular/common": "^5.0.0",
    "@ angular/compiler": "^5.0.0",
    "@ angular/compiler-cli": "^5.0.0",
    "@ angular/core": "^5.0.0",
    "@ angular/forms": "^5.0.0",
    "@ angular/http": "^5.0.0",
    "@ angular/material": "^2.0.0-beta.12",
    "@ angular/platform-browser": "^5.0.0",
    "@ angular/platform-browser-dynamic": "^5.0.0",
    "@ angular/platform-server": "^5.0.0",
    "@ angular/router": "^5.0.0",
    "@ ng-bootstrap/ng-bootstrap": "^1.0.0-beta.4",
    "@ types/mathjax": "0.0.31",
    "chart.js": "^2.6.0",
    "core-js": "^2.4.1",
    "markdown-it": "^8.4.0",
    "markdown-it-katex": "^2.0.3",
    "mathjax": "^2.7.1",
    "ng2-charts": "^1.6.0",
    "ng2-cookies": "^1.0.11",
    "ng2-file-upload": "^1.2.1",
    "ng2-img-tools": "^1.0.4",
    "ngx-chips": "^1.5.3",
    "rxjs": "^5.5.2",
    "typescript": "^2.4.2",
    "zone.js": "^0.8.4"
  },

this error will happen,how to fix this problem?

**Comment by bergben** [comment]
Hey @kaxu, unfortunately I was unable to identify the reason for this in my spare time today... 
I can check it out on Saturday or more likely Sunday in further depth.

**Comment by kaxu** [comment]
ok,thx

**Comment by wangchong666** [comment]
+1 in ionic3

**Comment by spersico** [comment]
+1 in Angular 5.1.0, a few days ago this worked...

**Comment by dgaletto** [comment]
If you want to continue developing you can try ng serve --aot

I'm busy this week, but I'll try to help with the error.

**Comment by dgaletto** [comment]
The error was reported in angular: angular/angular#20375

**Comment by oixan** [comment]
How can i fix this error temporarily to let the project work?
i cant run ng serve --aot because i have other errors to resolve and with aot i cant see the full description of the error.

**Comment by bergben** [comment]
Hi guys, thanks for your patience. I just fixed this in 1.1.2.
Turns out you have to set typescript to version `2.4.2` in package.json, as never versions of TS don't work with ngc yet.
