### ISSUE TITLE
problem forng2-img-max 

### ISSUE THREAD

**Issue by zgliuhouqing** [bergben/ng2-img-tools#23]
I have a problem when build android,    Metadata version mismatch for module ......../node_modules/ng2-img-max/dist/src/img-exif.service.d.ts, found version 4, expected 3.I don't know how to solve it

**Comment by marker004** [comment]
I have a similar issue. Building my project with Ng2ImgToolsModule in my app.module will not compile, but it will work and compile upon save of any other angular file. I am using Angular 4.2.4.

**Comment by sdsharma** [comment]
For Angular 4 compatibility downgrade ng2-img-max to version 2.1.6 and ng2-img-tools to version 1.1.0. The recent updates for Angular 5 broke it on 4.

**Comment by bergben** [comment]
Hey guys, as @sdsharma suggests you have to use an older version of ng2-img-tools on older versions of Angular.
