### ISSUE TITLE
Cannot read property 'result' of undefined

### ISSUE THREAD

**Issue by theHimanshuShekhar** [bergben/ng2-img-tools#28]
Image compression works without errors but for some images it throws the following error.
I have tried this with a lot of random images and it throws this error 1/10 times.
I cannot figure out why it doesn't work with particular images.
All images are of type jpeg.
![error](https://user-images.githubusercontent.com/31435438/34398752-5ab88a7c-eba7-11e7-9eda-e2b358f34877.PNG)

Code-
``` 
detectFiles(event) {
    if (event.target.files[0]) {
      this.progressname = event.target.files[0].name;
      this.compress(event.target.files[0]);
    }
  }

  compress(image) {
    this.ng2ImgToolsService.compress([image], 1).subscribe(
      result => {
        console.log('Image compressed.');
        this.processedImage = result;
        this.uploadImage();
      },
      error => {
        console.log('Compression error', error);
      });
  }
```
I am really new to Angular so I realize this may be something I am doing wrong.

**Comment by bergben** [comment]
Hey @theHimanshuShekhar. Could you click on the first link of the stack trace and tell me where this error is happening exactly? So I can investigate this issue better, thanks!
