### ISSUE TITLE
Handle errors in subscribe error not next

### ISSUE THREAD

**Issue by JonathanYates** [bergben/ng2-img-tools#3]
Very good. Except errors should be send to the error handler of subscribe not next. Errors should not be handled by the next handler of an observable. Should be:

this.ng2ImgToolsService.resize([someImage], 2000, 1000).subscribe(file => {
  // resized file handler
}, err => {
  // handle error
}, () => {
  // handler when we are all done
});

Which would be much cleaner.

**Comment by bergben** [comment]
Please excuse the delay @JonathanYates, I was very busy the last few weeks. Version 0.2.0 solves this issue: https://github.com/bergben/ng2-img-tools/releases/tag/0.2.0
Thanks for pointing it out, I appreciate it!
