### ISSUE TITLE
Cannot find module 'ng2-pica/ng2-pica'

### ISSUE THREAD

**Issue by senategit** [bergben/ng2-img-tools#34]
![image](https://user-images.githubusercontent.com/32482980/43136903-53959930-8f74-11e8-8b74-3a76f736deb3.png)

**Comment by simpsojo** [comment]
I see the same error:

ERROR in node_modules/ng2-img-max/dist/src/img-maxpx-size.service.d.ts(2,32): error TS2307: Cannot find module 'ng2-pica/ng2-pica'.


To reproduce (using latest angular-cli): 

ng new test
cd test
npm install ng2-img-tools
npm install

add import to app.module.ts:
  1. beneath BrowserModule add: ", Ng2ImgMaxModule"
  2. add import: { Ng2ImgMaxModule } from 'ng2-img-max'; at the top of the page

ng serve

**Comment by flashjpr** [comment]
+1, same error here

**Comment by oceankai** [comment]
same error here

**Comment by vishnupe** [comment]
+1, Same here

**Comment by Shakell** [comment]
Same error

**Comment by bergben** [comment]
should be fixed with the most recent version now! :)
