### ISSUE TITLE
ERROR Error: Uncaught (in promise): ReferenceError: EXIF is not defined

### ISSUE THREAD

**Issue by alignsoft** [bergben/ng2-img-tools#35]
When I'm processing images, I'm getting the following error:

`ERROR Error: Uncaught (in promise): ReferenceError: EXIF is not defined
`

This was working previously, however I'm not sure when it broke - it's definitely been working in Angular 6.x, but I may not have tested it since 6.0.x - I can't be sure.

I've noticed there was a thread on the ng2-img-max repo regarding this issue towards the end of 2017, and I'm wondering if the fix there was applied to this library as well.

I'm currently using Angular 6.1.2, and ng-img-tools 1.1.4

I tried installing exif-js: 2.3.0, but that had no impact.

**Comment by bergben** [comment]
Please try with 1.1.5, should fix the problem!
