### ISSUE TITLE
handling compress several images

### ISSUE THREAD

**Issue by danyyacoub** [bergben/ng2-img-tools#5]
Is there any example where there is handling of compress for several images?

The response of the subscription is always one of the images,

You did mention in the documentation

> Method to compress an image. This reduces the quality of an image down until it fits a certain fileSize which is given as maxSizeInMB. Set ignoreAlpha to true if you want to ignore the alpha channel for png images and compress them nonetheless (not recommended - the alpha channel will be lost and the resulting image might differ from the original image). Returns an observable that for every file given, onNext receives either a File when everything went as planned or an error Object if something went wrong. 

But honestly I didn't know how to implement it (maybe my lack of knowledge in observables in angular 2)

**Comment by bergben** [comment]
Yes, you get them one by one. Once the compression is complete for any one of them it is received by the Observable onNext. 

```
this.ng2ImgToolsService.resize([someImage, someImage2, someImage3], 2).subscribe(result => {
            //all good, result is a file
            //result will be for all of the input images
            this.compressedImages.push(result);
        }, error => {
            //something went wrong 
            //use result.compressedFile or handle specific error cases individually
        });
```

Unfortunately there is no `onComplete` implemented for the observable, you could count manually though...
