### ISSUE TITLE
Application freeze when resize

### ISSUE THREAD

**Issue by dewolft** [bergben/ng2-img-tools#7]
Hello,

there is a way for show a wait image during the "resize" operation is performed? i want to add a Wait class for show an image during the resize process but during the resize operation is execute application freeze... 

this is my code : 

     document.getElementsByName('imLoad')[0].classList.add('loading') ;  // class that show wait image
     this.ng2ImgToolsService.resize([event.target.files[0]], 1200, 1200).subscribe(result => {
            document.getElementsByName('imLoad')[0].classList.remove('loading') ;
        }, error => {
            this[errorbox] = error.reason ;
            document.getElementsByName('imLoad')[0].classList.remove('loading') ;
            console.log(error) ;
            // something went wrong 
            // use result.compressedFile or handle specific error cases individually
        }) ;

thanks for any help you'll provide to me :)

**Comment by bergben** [comment]
Hi @dewolft  

there is no "wait image" or loading indicator implemented as the purpose of this library is to merely provide a service. You can easily implement one yourself though. 
I think the problem is that you are doing it by manipulating the DOM, which you should really try to avoid in Angular (should be in the Style Guides or Best Practices somewhere for sure). If you want to add a class to a DOM node for certain rules only then you should use `ngClass`: https://angular.io/docs/ts/latest/api/common/index/NgClass-directive.html

Which would result in something like this:

```
 loading:boolean=false; 
 [...]
 public resizeImage(event):void{
    this.loading=true;
    this.ng2ImgToolsService.resize([event.target.files[0]], 1200, 1200).subscribe(result => {
       this.loading=false;
      //do something with the result
    }, error => {
        this.loading=false;
        this.errorBox = error.reason ;
        console.error(error) ;
    }) ;
 }
```

and in your markup add
``` [ngClass]="{'loading':loading}" ```


Please let me know if this solves your issue :)

**Comment by RathodGirish** [comment]
I am also getting error when try to implement in safari browser:

{
"resizedFile": {},
"reason": {
"line": 20562,
"column": 45,
"sourceURL": "http://192.168.1.3:4200/1.chunk.js",
"__zone_symbol__currentTask": {
"type": "microTask",
"state": "notScheduled",
"source": "Promise.then",
"zone": "",
"cancelFn": null,
"runCount": 0
}
},
"error": "PICA_ERROR"
}

Any suggestions?

**Comment by dewolft** [comment]
No I didn't solve... image and even CSS element freeze during resize processor. I don't know why.

The example didn't solve problem

**Comment by RathodGirish** [comment]
OK @dewolft 
@bergben Is there any other solution?
Please suggest.

**Comment by bergben** [comment]
Hey guys, 

I'll create a plunkr later today to reproduce this issue.

**Comment by RathodGirish** [comment]
OK that would be great

**Comment by bergben** [comment]
A quick update:

I was able to identify the problem. I wasn't aware that the File constructor is not supported for IE and Safari and furthermore it isn't even included in the polyfills. A polyfill for Canvas.toBlob is also required. 

Anyhow, I am changing my repositories to use the Blob constructor and cast it to a File for full TypeScript support. 

I already did that for the resizing, also the "showing a loading indicator" is solved in this plunkr: http://plnkr.co/edit/HRi5rQEDCBZb59a0lcPe

I will release a new version in the next few hours!

Thank you all for reporting this issue and helping to improve this project! 

**It would be great if someone of you could test the plunkr resizing in Safari. I don't have a Mac so testing it there is a bit tricky.**

**Comment by bergben** [comment]
I have just realeased 1.0.4 which should resolve this issue: https://github.com/bergben/ng2-img-tools/releases/tag/1.0.4

**Comment by bolerap** [comment]
Hi @bergben I've tested your demo http://plnkr.co/edit/HRi5rQEDCBZb59a0lcPe on safari 10.1.1 but it still error, this is a apart of error message on javascript console "Resize error:
Object

error: "PICA_ERROR"

reason: Error: macroTask 'HTMLCanvasElement.toBlob': can not transition to 'running', expecting state 'scheduled', was 'scheduling'.

resizedFile: File {name: "awesome-beautiful-wallpaper_124413582_294.jpg", lastModified: 1497845796000, size: 594655, type: "image/jpeg", slice: function}

Object Prototype"

**Comment by bergben** [comment]
@thanhngvpt Thanks for testing. I have tested it myself now too, however there seems to be a problem with whatever available polyfill that I use for `HTMLCanvasElement.toBlob()` and zone.js. I don't have the time to dig further into this issue, also Apple is making it difficult to test for Safari. So neither do I have the patience to test in Virtual machines. Pull requests are welcome.

**Comment by bsmithb2** [comment]
Hi @bergben  - Just wondering - are you intending on fixing this issue? It breaks on all Safari browsers including IOS which makes it not very useful - I was so close to having the perfect fix to my issue... 

Thanks for putting this stuff up its awesome!

**Comment by bolerap** [comment]
@bsmithb2 you can try this https://gist.github.com/thanhngvpt/a7fe3241f2ede28faf62c94052abafef before it fully fixed

**Comment by bsmithb2** [comment]
@thanhngvpt Thankyou David! I'll give it a shot!

**Comment by daghelge** [comment]
Hi @bsmithb2, did you test the gist? I've hit a wall here, and it would be VERY nice to get this working on Safari / IOS :) 

@bergben, any chance of you looking into this in the near future? I reeeeeally appreciate the work you have put into the library!

**Comment by bsmithb2** [comment]
@daghelge we ended up using code including Exif data transforms. Please see https://gist.github.com/bsmithb2/ded60680b5aef3d6b0c33028c62027d6

**Comment by Vi-dot** [comment]
It looks like the polyfill [JavaScript-Canvas-to-Blob](https://github.com/blueimp/JavaScript-Canvas-to-Blob) isn't well included.

I tested these pages on IOS : 
- [JavaScript-Canvas-to-Blob test page](https://blueimp.github.io/JavaScript-Canvas-to-Blob/test/) -> works fine
- [ng2-img-max Plnkr](http://plnkr.co/edit/HRi5rQEDCBZb59a0lcPe?p=preview) -> not working when resizing, compress... (PICA_ERROR)
- my project using angular-cli -> not working when resizing (Error: Uncaught in promise)

Then for each one, I printed functions toBlob() and dataURLtoBlob() in debug console.
-  For [JavaScript-Canvas-to-Blob test page](https://blueimp.github.io/JavaScript-Canvas-to-Blob/test/), functions look the same as they should be ([canvas-to-blob.js](https://github.com/blueimp/JavaScript-Canvas-to-Blob/blob/master/js/canvas-to-blob.js))
- For [ng2-img-max Plnkr](http://plnkr.co/edit/HRi5rQEDCBZb59a0lcPe?p=preview), they are different, see dataURLtoBlob() below
```javascript
> dataURLtoBlob.toString()
< function (dataURI) {
                var byteString,
                    arrayBuffer,
                    intArray,
                    i,
                    mimeString,
                    bb;
                if (dataURI.split(',')[0].indexOf('base64') >= 0) {
                    // Convert base64 to raw binary data held in a string:
                    byteString = atob(dataURI.split(',')[1]);
                } else {
                    // Convert base64/URLEncoded data component to raw binary data:
                    byteString = decodeURIComponent(dataURI.split(',')[1]);
                }
                // Write the bytes of the string to an ArrayBuffer:
                arrayBuffer = new ArrayBuffer(byteString.length);
                intArray = new Uint8Array(arrayBuffer);
                for (i = 0; i < byteString.length; i += 1) {
                    intArray[i] = byteString.charCodeAt(i);
                }
                // Separate out the mime component:
                mimeString = dataURI.split(',')[0].split(':')[1].split(';')[0];
                // Write the ArrayBuffer (or ArrayBufferView) to a blob:
                if (hasBlobConstructor) {
                    return new Blob(
                        [hasArrayBufferViewSupport ? intArray : arrayBuffer],
                        {type: mimeString}
                    );
                }
                bb = new BlobBuilder();
                bb.append(arrayBuffer);
                return bb.getBlob(mimeString);
            }
```
- For my project using angular-cli, toBlob() and dataURLtoBlob() does not exist at all.

To solve it for angular-cli, we may need to import or require [JavaScript-Canvas-to-Blob](https://github.com/blueimp/JavaScript-Canvas-to-Blob) in polyfills.ts.

**Comment by bergben** [comment]
@dewolft @RathodGirish  @thanhngvpt  @bsmithb2  @daghelge 
I have just tested the demo in Safari and it seems to work after modifying the underlying dependency for pica. Could you please give it a try too?
