### ISSUE TITLE
Using plugin with cordova

### ISSUE THREAD

**Issue by FredeHo** [bergben/ng2-img-tools#9]
Calling resize/compress (maybe more) in an **Android** App (tested on Android 5 & 6 & 7) seems to do nothing. Forever waiting on the observable. No errors. PWA in Browser and iOS works fine. 
Can anyone help me?

ng2-img-tools - 1.0.4
ng2-img-max - 2.1.4
ng2-pica - 1.0.6
Cordova CLI - 7.0.1
Ionic Framework - 3.0.1
Ionic CLI - 2.2.0
Node - 6.10.3
(those may be relevant, idk)

**Comment by bergben** [comment]
Hey there @FredeHo,

I have tested it and can confirm it's not working on Android Emulator. However it works just fine if you connect an actual android device and run your app on that device. Seems to be a problem with the emulator(s). The error code appearing in Android Monitor is: `Fatal signal 4 (SIGILL), code 2, fault addr 0x92b578d5`. Google that code and you'll find lots of people reporting that error always somehow being connected to the emulator. 

Hope this helps you :)

**Comment by FredeHo** [comment]
Sadly im running on actual devices, never emulator :(
Thanks for your help tho!

**Comment by bergben** [comment]
I see. Can you share your code @FredeHo ?

**Comment by FredeHo** [comment]
Sure, the file im using straight comes out of a file input (intern, extern, camera doesnt seem to matter).
```
// Resizing the image
this.ng2ImgToolsService.resize([file], 1280, 1280).subscribe(res => {
    // Compressing the resized image 
    this.ng2ImgToolsService.compress([res], 0.3, true).subscribe(res => {
      // Get blob and return it
      let reader = new FileReader();
      reader.onload = () => {
        let result = reader.result;
        let blob = new Blob([new Uint8Array(result)], {
          type: "image/jpeg"
        });
        resolve(blob);
      };
      reader.readAsArrayBuffer(res);
    }
    
    // Error handling etc
```

It never passes the resize cmd tho and no error occures :/

**Comment by bergben** [comment]
I am not sure what the problem could be so I have created a repo with my sample ionic app for ng2-img-tools: https://github.com/bergben/ionic-img-tools-sample

Can you please clone that repo, test that code on your android device and then compare what the differences could be (if it works) @FredeHo ?

**Comment by FredeHo** [comment]
Okay tested your sample app. Everything is working fine (except sources like googledrive, but thats not a problem with your plugin i guess).

It seems the reason it didnt work for me is the **Content-Security-Policy**. Without specifying any - like your sample app - everythings alright. I couldn't find out how I need to set up the CSP to make it work though...

Anyways, it doesnt seem to be an issue with your plugin itself so you may want to close it.
Keep up the good work, love your plugins!

**Comment by bergben** [comment]
Thanks for reporting back. I hope you'll be able to work out the CSP. Just another hint, keep in mind that the resizing is actually done by `pica`: https://github.com/nodeca/pica. I don't really know if that will help you but just wanted to make sure to mention it. :)
